// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAco32Ka2qZBAnwstf74u_D71XWRwDBhCA',
    appId: '1:284390772682:web:3d65eb1cf626e97a140933',
    messagingSenderId: '284390772682',
    projectId: 'tik-tok-ganadara',
    authDomain: 'tik-tok-ganadara.firebaseapp.com',
    storageBucket: 'tik-tok-ganadara.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjP2r0YchPPzQTg7CUQJeq1t769bSz67Y',
    appId: '1:284390772682:android:7c28721c2159599d140933',
    messagingSenderId: '284390772682',
    projectId: 'tik-tok-ganadara',
    storageBucket: 'tik-tok-ganadara.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8bkxYByPM8BXpazctZ_K6qc9zGUisuoI',
    appId: '1:284390772682:ios:0d70656166e02249140933',
    messagingSenderId: '284390772682',
    projectId: 'tik-tok-ganadara',
    storageBucket: 'tik-tok-ganadara.firebasestorage.app',
    iosBundleId: 'com.example.threadClone',
  );

}